src/t1/webpages/config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root 'pages#index'
end

src/t1/webpages/app/models/page.rb
class Page < ActiveRecord::Base
  validates_presence_of :title, :slug, :description, :body, :author
end

src/t1/webpages/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

src/t1/webpages/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end
  
  def show
  end
   
  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
    redirect_to pages_path
    else
    render :new
    end
  end

  def edit
  end

  def update
    if @page.update(page_params)
    redirect_to pages_path
    else
    render :new
    end
  end

  def destroy
    if @page.destroy
    redirect_to pages_path
    end
  end

  private

    def set_page
    @page = Page.find(params[:id])
    end

    def page_params
    params.require(:page).permit(:title, :slug, :description, :body, :author)
    end
end

src/t1/webpages/app/helpers/application_helper.rb
module ApplicationHelper
end

src/t1/webpages/app/helpers/pages_helper.rb
module PagesHelper
end

src/t1/webpages/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webpages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

src/t1/webpages/app/views/pages/_form.html.erb
<div>
  <%= form_for @page do |f| %>
    <% if @page.errors.any? %>
      <div class="errors">
        <ul class="alert error">
          <% @page.errors.full_messages.each  do |msg| %>
           <li><%= msg %></li>
    <% end %>
        </ul>
      </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :slug %>
  <%= f.text_field :slug %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <div class="actions">
      <%= f.submit %>
  </div>

<% end %>

</div>

src/t1/webpages/app/views/pages/_page.html.erb
<% @pages.each do |page| %>
      <tr>
        <h2><%= link_to page.title, page %></h2>
        </h4><%= page.author %></h4>
        
        <p><%= page.body %></p>
        <p><%= page.description %></p>
        <p><%= page.body %></p>
        <p>
          <%= link_to 'Edit', edit_page_path(page) %>
          <%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
<% end %>

src/t1/webpages/app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

src/t1/webpages/app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'page' %>
  </tbody>
</table>

<br>

<h2><%= link_to 'New Post', new_page_path %></h2>

src/t1/webpages/app/views/pages/new.html.erb
<h1>New Paget</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

src/t1/webpages/app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p class="h5">por:<%= @page.author %></p>
<p><%= @page.body %></p>
<p><%= @page.description %></p>

<h4><%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %></h4>